name: Flux Framework CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Flux Tests
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Cache Unity Library files
      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Step 3: Run the custom test method
      - name: Run Flux Tests
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          
          # La version d'Unity est toujours requise.
          unityVersion: '2022.3.10f1'
          
          # Notre commande personnalisée.
          customParameters: -nographics -logFile -executeMethod FluxFramework.Testing.FluxTestRunnerCli.RunTests

      # Step 4: Upload test logs
      - name: Upload Test Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test Execution Logs
          path: editor.log